# -*- coding: utf-8 -*-
"""MMDetection3D+KITTI_3D프로젝트.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LvkxKeWnfQdTW5Q6vIX821AaTI67IKWW

# 1. GPU/시스템 정보 확인
"""

# Commented out IPython magic to ensure Python compatibility.
# # GPU/시스템 정보 확인
# %%bash
# echo "========================================================================"
# echo "🖥️ 시스템 정보"
# echo "========================================================================"
# echo ""
# echo "📅 현재 시간: $(date '+%Y-%m-%d %H:%M:%S')"
# echo ""
# echo "🔧 GPU 정보:"
# nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader
# echo ""
# echo "🔧 CUDA 버전:"
# nvcc --version 2>/dev/null | grep "release" || echo "nvcc not found"
# echo ""
# echo "🔧 Python 버전:"
# python --version
# echo ""
# echo "🔧 디스크 공간:"
# df -h /content | tail -1 | awk '{print "   사용: " $3 " / " $2 " (" $5 " 사용중)"}'
# echo ""
# echo "========================================================================"

from google.colab import drive; drive.mount('/content/drive')

"""# 2. Miniconda + UV 설치"""

# Commented out IPython magic to ensure Python compatibility.
# # Miniconda + UV 설치
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "📦 Miniconda + UV 설치"
# echo "========================================================================"
# echo "📅 시작: $(date '+%H:%M:%S')"
# echo ""
# 
# # Miniconda 설치
# if [ ! -d "/content/conda" ]; then
#     echo "1️⃣ Miniconda 다운로드 및 설치..."
#     wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
#     bash /tmp/miniconda.sh -b -p /content/conda > /dev/null 2>&1
#     rm /tmp/miniconda.sh
#     echo "   ✅ Miniconda 설치 완료"
# else
#     echo "1️⃣ Miniconda 이미 설치됨"
# fi
# 
# # UV 설치 (base 환경에)
# if [ ! -f "/content/conda/bin/uv" ]; then
#     echo "2️⃣ UV 설치..."
#     /content/conda/bin/pip install uv -q
#     echo "   ✅ UV 설치 완료"
# else
#     echo "2️⃣ UV 이미 설치됨"
# fi
# 
# echo ""
# echo "📋 UV 버전:"
# /content/conda/bin/uv --version
# 
# echo ""
# echo "📅 완료: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 3. Anaconda ToS 동의 + Python 3.10 환경 생성"""

# Commented out IPython magic to ensure Python compatibility.
# # Anaconda ToS 동의 + Python 3.10 conda 환경 생성
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "🐍 Python 3.10 conda 환경 생성"
# echo "========================================================================"
# echo "📅 시작: $(date '+%H:%M:%S')"
# echo ""
# 
# source /content/conda/bin/activate
# 
# # Anaconda Terms of Service 동의
# echo "1️⃣ Anaconda Terms of Service 동의..."
# conda config --set solver classic 2>/dev/null || true
# echo "y" | conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main 2>/dev/null || true
# echo "y" | conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r 2>/dev/null || true
# conda config --add channels conda-forge 2>/dev/null || true
# conda config --set channel_priority flexible 2>/dev/null || true
# echo "   ✅ 설정 완료"
# echo ""
# 
# if [ ! -d "/content/conda/envs/openmmlab" ]; then
#     echo "2️⃣ openmmlab 환경 생성 중..."
#     conda create -n openmmlab python=3.10 -c conda-forge -y -q 2>&1 | tail -5
#     echo "   ✅ 환경 생성 완료"
# else
#     echo "2️⃣ openmmlab 환경 이미 존재"
# fi
# 
# echo ""
# echo "📋 Python 버전 확인:"
# /content/conda/envs/openmmlab/bin/python --version
# echo ""
# echo "📅 완료: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 4. NumPy 1.26.4 설치"""

# Commented out IPython magic to ensure Python compatibility.
# # NumPy 1.26.4 설치
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "📦 NumPy 1.26.4 설치"
# echo "========================================================================"
# echo "📅 시작: $(date '+%H:%M:%S')"
# echo ""
# 
# PY=/content/conda/envs/openmmlab/bin/python
# UV=/content/conda/bin/uv
# 
# echo "1️⃣ NumPy 설치 중..."
# $UV pip install numpy==1.26.4 --python $PY -q
# 
# echo ""
# echo "📋 NumPy 버전 확인:"
# $PY -c "import numpy; print(f'   NumPy: {numpy.__version__}')"
# echo ""
# echo "📅 완료: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 5. PyTorch 2.1.2 + CUDA 11.8 설치"""

# Commented out IPython magic to ensure Python compatibility.
# # PyTorch 2.1.2 + CUDA 11.8 설치
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "🔥 PyTorch 2.1.2 + CUDA 11.8 설치"
# echo "========================================================================"
# echo "📅 시작: $(date '+%H:%M:%S')"
# echo ""
# 
# PY=/content/conda/envs/openmmlab/bin/python
# UV=/content/conda/bin/uv
# 
# echo "1️⃣ PyTorch 설치 중 (약 1분 소요)..."
# $UV pip install torch==2.1.2 torchvision==0.16.2 \
#     --index-url https://download.pytorch.org/whl/cu118 \
#     --python $PY -q
# 
# echo ""
# echo "📋 설치 확인:"
# $PY -c "
# import torch
# print(f'   PyTorch: {torch.__version__}')
# print(f'   CUDA 사용 가능: {torch.cuda.is_available()}')
# if torch.cuda.is_available():
#     print(f'   GPU: {torch.cuda.get_device_name(0)}')
#     print(f'   CUDA 버전: {torch.version.cuda}')
# "
# 
# echo ""
# echo "📅 완료: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 6. OpenMMLab 스택 설치"""

# Commented out IPython magic to ensure Python compatibility.
# # OpenMMLab 스택 설치 (mmcv, mmengine, mmdet)
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "📦 OpenMMLab 스택 설치"
# echo "========================================================================"
# echo "📅 시작: $(date '+%H:%M:%S')"
# echo ""
# 
# PY=/content/conda/envs/openmmlab/bin/python
# UV=/content/conda/bin/uv
# 
# echo "1️⃣ mmcv 2.1.0 설치 중..."
# $UV pip install mmcv==2.1.0 \
#     -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1/index.html \
#     --python $PY -q
# echo "   ✅ mmcv 설치 완료"
# 
# echo "2️⃣ mmengine 설치 중..."
# $UV pip install mmengine==0.10.7 --python $PY -q
# echo "   ✅ mmengine 설치 완료"
# 
# echo "3️⃣ mmdet 설치 중..."
# $UV pip install mmdet==3.3.0 --python $PY -q
# echo "   ✅ mmdet 설치 완료"
# 
# echo ""
# echo "📋 설치 확인:"
# $PY -c "
# import mmcv
# import mmengine
# import mmdet
# print(f'   mmcv: {mmcv.__version__}')
# print(f'   mmengine: {mmengine.__version__}')
# print(f'   mmdet: {mmdet.__version__}')
# "
# 
# echo ""
# echo "📅 완료: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 7. MMDetection3D v1.4.0 설치 + 패치"""

# Commented out IPython magic to ensure Python compatibility.
# # MMDetection3D v1.4.0 설치 + np.long 패치
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "📦 MMDetection3D v1.4.0 설치"
# echo "========================================================================"
# echo "📅 시작: $(date '+%H:%M:%S')"
# echo ""
# 
# PY=/content/conda/envs/openmmlab/bin/python
# UV=/content/conda/bin/uv
# 
# cd /content
# 
# # 클론
# if [ ! -d "mmdetection3d" ]; then
#     echo "1️⃣ MMDetection3D 클론 중..."
#     git clone -b v1.4.0 --depth 1 https://github.com/open-mmlab/mmdetection3d.git 2>/dev/null
#     echo "   ✅ 클론 완료"
# else
#     echo "1️⃣ MMDetection3D 이미 존재"
# fi
# 
# # 런타임 의존성 설치
# echo "2️⃣ 런타임 의존성 설치 중..."
# cd mmdetection3d
# $UV pip install -r requirements/runtime.txt --python $PY -q 2>/dev/null || true
# $UV pip install "nuscenes-devkit==1.1.11" --python $PY -q 2>/dev/null || true
# echo "   ✅ 의존성 설치 완료"
# 
# # np.long → np.int64 패치
# echo "3️⃣ NumPy 호환성 패치 적용 중..."
# find /content/mmdetection3d -name "*.py" -exec grep -l "np\.long[^a-z]" {} \; 2>/dev/null | while read f; do
#     sed -i 's/np\.long\([^a-z]\)/np.int64\1/g' "$f"
# done
# echo "   ✅ np.long → np.int64 패치 완료"
# 
# echo ""
# echo "📋 설치 확인:"
# export PYTHONPATH=/content/mmdetection3d:$PYTHONPATH
# $PY -c "import mmdet3d; print(f'   mmdet3d: {mmdet3d.__version__}')"
# 
# echo ""
# echo "📅 완료: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 8. numba 0.56.4 설치 (PTX 호환성) + 의존성 검증"""

# Commented out IPython magic to ensure Python compatibility.
# # numba 설정 (CUDA 비활성화 + CPU fallback)
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "🔧 numba 설정 (CUDA 호환성 문제 해결)"
# echo "========================================================================"
# echo "📅 시작: $(date '+%H:%M:%S')"
# echo ""
# 
# PY=/content/conda/envs/openmmlab/bin/python
# UV=/content/conda/bin/uv
# export PYTHONPATH=/content/mmdetection3d:$PYTHONPATH
# 
# # numba 0.57.1 설치 (중간 버전)
# echo "1️⃣ numba 0.57.1 + llvmlite 0.40.1 설치..."
# $UV pip uninstall numba llvmlite -y --python $PY -q 2>/dev/null || true
# $UV pip install numba==0.57.1 llvmlite==0.40.1 --python $PY -q
# echo "   ✅ numba 0.57.1 설치 완료"
# 
# # numba 캐시 삭제
# echo ""
# echo "2️⃣ numba 캐시 삭제..."
# rm -rf ~/.cache/numba
# rm -rf /root/.cache/numba
# rm -rf /content/mmdetection3d/mmdet3d/evaluation/functional/kitti_utils/__pycache__
# find /content/mmdetection3d -name "*.nbc" -delete 2>/dev/null || true
# find /content/mmdetection3d -name "*.nbi" -delete 2>/dev/null || true
# echo "   ✅ 캐시 삭제 완료"
# 
# # ⚠️ 핵심: numba CUDA 비활성화 설정 파일 생성
# echo ""
# echo "3️⃣ numba CUDA 비활성화 설정..."
# mkdir -p /content/conda/envs/openmmlab/etc/conda/activate.d
# cat > /content/conda/envs/openmmlab/etc/conda/activate.d/env_vars.sh << 'ENVEOF'
# #!/bin/bash
# export NUMBA_DISABLE_CUDA=1
# ENVEOF
# chmod +x /content/conda/envs/openmmlab/etc/conda/activate.d/env_vars.sh
# echo "   ✅ NUMBA_DISABLE_CUDA=1 설정 완료"
# 
# echo ""
# echo "4️⃣ 의존성 확인:"
# $PY << 'EOF'
# import os
# os.environ['NUMBA_DISABLE_CUDA'] = '1'  # Python 내에서도 설정
# 
# import sys
# print(f"   Python: {sys.version.split()[0]}")
# 
# import numpy as np
# print(f"   NumPy: {np.__version__}")
# 
# import torch
# print(f"   PyTorch: {torch.__version__}")
# print(f"   CUDA available: {torch.cuda.is_available()}")
# 
# import mmcv
# print(f"   mmcv: {mmcv.__version__}")
# 
# import mmengine
# print(f"   mmengine: {mmengine.__version__}")
# 
# import mmdet
# print(f"   mmdet: {mmdet.__version__}")
# 
# import mmdet3d
# print(f"   mmdet3d: {mmdet3d.__version__}")
# 
# import numba
# print(f"   numba: {numba.__version__}")
# print(f"   NUMBA_DISABLE_CUDA: {os.environ.get('NUMBA_DISABLE_CUDA', 'not set')}")
# 
# import llvmlite
# print(f"   llvmlite: {llvmlite.__version__}")
# 
# if torch.cuda.is_available():
#     print(f"\n   GPU: {torch.cuda.get_device_name(0)}")
#     print(f"   GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")
# EOF
# 
# echo ""
# echo "📅 완료: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 9. KITTI 데이터셋 다운로드"""

# Commented out IPython magic to ensure Python compatibility.
# # KITTI 데이터셋 다운로드
# %%bash
# set -e
# 
# echo "========================================================================"
# echo "📥 KITTI 3D 데이터셋 다운로드"
# echo "========================================================================"
# echo "📅 시작 시간: $(date '+%H:%M:%S')"
# echo ""
# 
# # aria2 설치
# echo "1️⃣ aria2 설치 중..."
# apt-get update -qq && apt-get install -y aria2 -qq 2>/dev/null
# echo "   ✅ aria2 설치 완료"
# echo ""
# 
# DATA_ROOT=/content/data/kitti
# mkdir -p ${DATA_ROOT}
# cd ${DATA_ROOT}
# 
# # 이미 완료 확인
# if [ -d "training/velodyne" ] && [ $(ls training/velodyne/*.bin 2>/dev/null | wc -l) -gt 7000 ]; then
#     echo "✅ KITTI 데이터가 이미 존재합니다!"
#     echo "   Training: $(ls training/velodyne/*.bin | wc -l) samples"
#     echo "   Testing: $(ls testing/velodyne/*.bin 2>/dev/null | wc -l) samples"
#     exit 0
# fi
# 
# echo "📋 다운로드할 파일:"
# echo "   1. data_object_calib.zip (~16MB)"
# echo "   2. data_object_label_2.zip (~5MB)"
# echo "   3. data_object_image_2.zip (~12GB)"
# echo "   4. data_object_velodyne.zip (~29GB)"
# echo ""
# echo "⏱️ 예상 소요 시간: 20-40분"
# echo ""
# echo "========================================================================"
# 
# download_and_extract() {
#     local filename=$1
#     local desc=$2
#     local url="https://s3.eu-central-1.amazonaws.com/avg-kitti/${filename}"
# 
#     echo ""
#     echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
#     echo "🔽 ${filename} - ${desc}"
#     echo "   시작: $(date '+%H:%M:%S')"
# 
#     aria2c -x 16 -s 16 -k 1M \
#         --summary-interval=60 \
#         --console-log-level=notice \
#         --download-result=hide \
#         "${url}" -o "${filename}" 2>&1 | grep -E "(\[#|Download)" || true
# 
#     if [ -f "${filename}" ]; then
#         echo "   📦 압축 해제 중..."
#         unzip -q -o "${filename}"
#         rm -f "${filename}"
#         echo "   ✅ 완료: $(date '+%H:%M:%S')"
#     fi
# }
# 
# echo ""
# echo "2️⃣ 파일 다운로드 시작"
# 
# download_and_extract "data_object_calib.zip" "Calibration"
# download_and_extract "data_object_label_2.zip" "Labels"
# download_and_extract "data_object_image_2.zip" "RGB Images"
# download_and_extract "data_object_velodyne.zip" "LiDAR Point Cloud"
# 
# echo ""
# echo "3️⃣ ImageSets 다운로드"
# mkdir -p ImageSets
# for split in train val test; do
#     if [ ! -f "ImageSets/${split}.txt" ]; then
#         wget -q https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/${split}.txt -O ImageSets/${split}.txt
#     fi
#     echo "   ✅ ${split}.txt: $(wc -l < ImageSets/${split}.txt) samples"
# done
# 
# echo ""
# echo "========================================================================"
# echo "✅ KITTI 다운로드 완료!"
# echo "========================================================================"
# echo "📊 데이터 통계:"
# echo "   Training: $(ls training/velodyne/*.bin 2>/dev/null | wc -l) samples"
# echo "   Testing: $(ls testing/velodyne/*.bin 2>/dev/null | wc -l) samples"
# echo "   디스크 사용량: $(du -sh ${DATA_ROOT} | cut -f1)"
# echo "📅 완료 시간: $(date '+%H:%M:%S')"
# echo "========================================================================"

"""# 11. 데이터 전처리"""

# KITTI 데이터 전처리 (실시간 로깅)
import subprocess
import os
from datetime import datetime

print("=" * 70)
print("🔄 KITTI 데이터 전처리")
print("=" * 70)
print(f"📅 시작 시간: {datetime.now().strftime('%H:%M:%S')}")
print()

# 심볼릭 링크 생성
os.makedirs('/content/mmdetection3d/data', exist_ok=True)
link_path = '/content/mmdetection3d/data/kitti'
if os.path.islink(link_path):
    os.remove(link_path)
elif os.path.exists(link_path):
    import shutil
    shutil.rmtree(link_path)
os.symlink('/content/data/kitti', link_path)
print("🔗 심볼릭 링크 생성 완료")
print()

print("📋 생성할 파일:")
print("   • kitti_infos_train.pkl")
print("   • kitti_infos_val.pkl")
print("   • kitti_dbinfos_train.pkl")
print("   • training/velodyne_reduced/")
print()
print("⏳ 전처리 시작 (약 10-15분 소요)...")
print("-" * 70)

env = os.environ.copy()
env['PYTHONPATH'] = '/content/mmdetection3d:' + env.get('PYTHONPATH', '')
env['PYTHONUNBUFFERED'] = '1'

cmd = [
    '/content/conda/envs/openmmlab/bin/python', '-u',
    '/content/mmdetection3d/tools/create_data.py', 'kitti',
    '--root-path', '/content/data/kitti',
    '--out-dir', '/content/data/kitti',
    '--extra-tag', 'kitti',
    '--workers', '2'
]

process = subprocess.Popen(
    cmd,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    env=env,
    text=True,
    bufsize=1,
    cwd='/content/mmdetection3d'
)

for line in iter(process.stdout.readline, ''):
    print(line, end='', flush=True)

process.wait()

print("-" * 70)
print()
print("=" * 70)
print("✅ 전처리 완료")
print("=" * 70)

import glob
print("\n📁 생성된 파일:")
for pkl in sorted(glob.glob('/content/data/kitti/*.pkl')):
    size = os.path.getsize(pkl) / 1024 / 1024
    print(f"   {os.path.basename(pkl)}: {size:.1f} MB")

reduced_dir = '/content/data/kitti/training/velodyne_reduced'
if os.path.exists(reduced_dir):
    count = len([f for f in os.listdir(reduced_dir) if f.endswith('.bin')])
    print(f"   velodyne_reduced/: {count} files")

print(f"\n📅 완료 시간: {datetime.now().strftime('%H:%M:%S')}")
print("=" * 70)

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# DRIVE_DIR="/content/drive/MyDrive/Colab Notebooks/3d_project"
# 
# cp "$DRIVE_DIR/pseudo_velodyne.tar.gz" /content/pseudo_velodyne.tar.gz
# # pth 파일명 길면 와일드카드로
# cp "$DRIVE_DIR/"*.pth /content/mvxnet_teacher.pth
# 
# ls -lah /content/pseudo_velodyne.tar.gz
# ls -lah /content/mvxnet_teacher.pth
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# mkdir -p /content/data/kitti/training/pseudo_velodyne
# 
# tar -xzf /content/pseudo_velodyne.tar.gz -C /content/data/kitti/training/pseudo_velodyne
# 
# # 000000.bin이 바로 보이는지 확인
# ls -lah /content/data/kitti/training/pseudo_velodyne | head
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# PSEUDO_ROOT="/content/data/kitti/training/pseudo_velodyne"
# TAR_PATH="/content/pseudo_velodyne.tar.gz"
# 
# # tar에서 첫 번째 .bin 경로를 보고, 폴더 depth 계산
# FIRST_BIN=$(tar -tzf "$TAR_PATH" | grep -m1 '\.bin$' || true)
# if [ -z "$FIRST_BIN" ]; then
#   echo "❌ tar 안에서 .bin 파일을 못 찾았어. 압축 파일이 맞는지 확인 필요"
#   exit 1
# fi
# 
# STRIP=$(echo "$FIRST_BIN" | awk -F/ '{print NF-1}')  # 경로의 디렉토리 개수
# echo "✅ FIRST_BIN = $FIRST_BIN"
# echo "✅ STRIP_COMPONENTS = $STRIP"
# 
# # 다시 깔끔하게 풀기
# rm -rf "$PSEUDO_ROOT"
# mkdir -p "$PSEUDO_ROOT"
# 
# if [ "$STRIP" -gt 0 ]; then
#   tar -xzf "$TAR_PATH" -C "$PSEUDO_ROOT" --strip-components="$STRIP"
# else
#   tar -xzf "$TAR_PATH" -C "$PSEUDO_ROOT"
# fi
# 
# echo "---- after extract (top) ----"
# ls -lah "$PSEUDO_ROOT" | head
# echo "---- find 000000.bin ----"
# find "$PSEUDO_ROOT" -maxdepth 2 -name "000000.bin" -print | head -n 5
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# ls -lah /content/mvxnet_teacher.pth
# ls -lah /content/data/kitti/training/pseudo_velodyne/000000.bin
# ls -lah /content/data/kitti/training/velodyne/000000.bin
# ls -lah /content/data/kitti/training/image_2/000000.png
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# PY="/content/conda/envs/openmmlab/bin/python"
# MMDET3D="/content/mmdetection3d"
# KITTI="/content/data/kitti"
# 
# CFG="$MMDET3D/configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class.py"
# TEACHER_CKPT="/content/mvxnet_teacher.pth"
# STUDENT_CKPT="$TEACHER_CKPT"
# 
# PSEUDO_DIR="$KITTI/training/pseudo_velodyne"
# FRAME_ID="000000"
# STAGE="middle"
# OUT_DIR="/content/bev_out"
# mkdir -p "$OUT_DIR"
# 
# export PYTHONPATH="/content/mmdetection3d:$PYTHONPATH"
# 
# cat > /content/extract_bev_mvxnet.py <<'PY'
# import os, re, copy, argparse, tempfile
# import numpy as np
# import torch
# 
# from mmengine.config import Config
# from mmengine.dataset import pseudo_collate
# from mmdet3d.apis import init_model
# from mmdet3d.registry import DATASETS
# 
# def zfill6(x) -> str:
#     s = str(x)
#     m = re.findall(r'\d+', s)
#     if m:
#         s = m[-1]
#     s = s[-6:]
#     return s.zfill(6)
# 
# def ensure_kitti_bin4(bin_path: str) -> str:
#     arr = np.fromfile(bin_path, dtype=np.float32)
#     if arr.size % 4 == 0:
#         return bin_path
#     if arr.size % 3 != 0:
#         raise ValueError(f"bin float count not divisible by 3 or 4: {bin_path} (floats={arr.size})")
#     pts3 = arr.reshape(-1, 3)
#     pts4 = np.concatenate([pts3, np.zeros((pts3.shape[0], 1), dtype=np.float32)], axis=1)
#     tmp = tempfile.NamedTemporaryFile(suffix=".bin", delete=False)
#     pts4.astype(np.float32).tofile(tmp.name)
#     return tmp.name
# 
# def set_lidar_path(data_info: dict, new_abs_path: str):
#     if 'lidar_points' in data_info and isinstance(data_info['lidar_points'], dict):
#         if 'lidar_path' in data_info['lidar_points']:
#             data_info['lidar_points']['lidar_path'] = new_abs_path
#             return
#     if 'pts_filename' in data_info:
#         data_info['pts_filename'] = new_abs_path
#         return
#     for k, v in data_info.items():
#         if isinstance(v, dict):
#             for kk in list(v.keys()):
#                 if 'lidar' in kk and 'path' in kk:
#                     v[kk] = new_abs_path
#                     return
#     raise KeyError("Could not find lidar path key in data_info")
# 
# def find_index_by_frame(dataset, frame_id: str) -> int:
#     target = zfill6(frame_id)
#     for i in range(len(dataset)):
#         info = dataset.get_data_info(i)
#         for key in ['sample_idx', 'image_idx', 'idx', 'frame_id']:
#             if key in info and zfill6(info[key]) == target:
#                 return i
#         try:
#             if 'lidar_points' in info and 'lidar_path' in info['lidar_points']:
#                 base = os.path.basename(info['lidar_points']['lidar_path'])
#                 if zfill6(os.path.splitext(base)[0]) == target:
#                     return i
#         except Exception:
#             pass
#         if 'images' in info and isinstance(info['images'], dict):
#             for caminfo in info['images'].values():
#                 p = caminfo.get('img_path', '')
#                 if p:
#                     base = os.path.basename(p)
#                     if zfill6(os.path.splitext(base)[0]) == target:
#                         return i
#     raise ValueError(f"Frame id {target} not found in dataset infos")
# 
# def pick_tensor(x):
#     if isinstance(x, torch.Tensor):
#         return x
#     if isinstance(x, dict):
#         for k in ['spatial_features', 'out', 'features', 'feat']:
#             if k in x and isinstance(x[k], torch.Tensor):
#                 return x[k]
#         for v in x.values():
#             if isinstance(v, torch.Tensor):
#                 return v
#     if isinstance(x, (list, tuple)):
#         for v in x:
#             t = pick_tensor(v)
#             if t is not None:
#                 return t
#     return None
# 
# def get_stage_module(model, stage: str):
#     if stage == 'middle' and hasattr(model, 'pts_middle_encoder'):
#         return model.pts_middle_encoder
#     if stage == 'backbone' and hasattr(model, 'pts_backbone'):
#         return model.pts_backbone
#     if stage == 'neck' and hasattr(model, 'pts_neck'):
#         return model.pts_neck
#     for name in ['pts_middle_encoder', 'pts_backbone', 'pts_neck']:
#         if hasattr(model, name):
#             return getattr(model, name)
#     raise AttributeError("No pts_* module found on model")
# 
# def to_meta(ds):
#     # Det3DDataSample/BaseDataElement -> metainfo dict
#     if isinstance(ds, dict):
#         return ds
#     if hasattr(ds, 'metainfo') and isinstance(ds.metainfo, dict):
#         return ds.metainfo
#     if hasattr(ds, 'to_dict'):
#         d = ds.to_dict()
#         return d if isinstance(d, dict) else {}
#     # 최후: attribute dict
#     return {}
# 
# def main():
#     ap = argparse.ArgumentParser()
#     ap.add_argument('--config', required=True)
#     ap.add_argument('--checkpoint', required=True)
#     ap.add_argument('--kitti_root', required=True)
#     ap.add_argument('--frame_id', required=True)
#     ap.add_argument('--lidar_override', default=None)
#     ap.add_argument('--stage', default='middle', choices=['middle','backbone','neck'])
#     ap.add_argument('--out', required=True)
#     ap.add_argument('--device', default='cuda:0')
#     args = ap.parse_args()
# 
#     cfg = Config.fromfile(args.config)
#     cfg.test_dataloader.dataset = copy.deepcopy(cfg.test_dataloader.dataset)
#     cfg.test_dataloader.dataset['data_root'] = args.kitti_root + '/'
# 
#     model = init_model(cfg, args.checkpoint, device=args.device)
#     model.eval()
# 
#     # ✅ (안전) point_fusion이 Det3DDataSample을 받아도 metainfo로 변환하도록 패치
#     try:
#         import mmdet3d.models.layers.fusion_layers.point_fusion as pf
#         _orig = pf.get_proj_mat_by_coord_type
#         def _patched(img_meta, coord_type):
#             if not isinstance(img_meta, dict) and hasattr(img_meta, 'metainfo'):
#                 img_meta = img_meta.metainfo
#             return _orig(img_meta, coord_type)
#         pf.get_proj_mat_by_coord_type = _patched
#     except Exception as e:
#         print("[WARN] point_fusion patch skipped:", repr(e))
# 
#     dataset = DATASETS.build(cfg.test_dataloader.dataset)
#     idx = find_index_by_frame(dataset, args.frame_id)
#     info = copy.deepcopy(dataset.get_data_info(idx))
# 
#     if args.lidar_override is not None:
#         fixed = ensure_kitti_bin4(args.lidar_override)
#         set_lidar_path(info, fixed)
# 
#     packed = dataset.pipeline(info)
#     batch = pseudo_collate([packed])
#     batch = model.data_preprocessor(batch, training=False)
# 
#     inputs = batch['inputs']
#     data_samples = batch['data_samples']
# 
#     # ✅ 핵심: Det3DDataSample 리스트 -> metainfo dict 리스트로 변환해서 넘김
#     img_metas = [to_meta(ds) for ds in data_samples]
# 
#     # hook으로 BEV 잡기
#     cache = {}
#     module = get_stage_module(model, args.stage)
# 
#     def hook_fn(_m, _inp, _out):
#         cache['out'] = _out
# 
#     h = module.register_forward_hook(hook_fn)
#     with torch.no_grad():
#         # ✅ data_samples 대신 img_metas(dict list)를 넘긴다
#         _ = model.extract_feat(inputs, img_metas)
#     h.remove()
# 
#     bev = pick_tensor(cache.get('out', None))
#     if bev is None:
#         raise RuntimeError("Could not capture BEV tensor from hook output.")
# 
#     os.makedirs(os.path.dirname(args.out), exist_ok=True)
#     torch.save({'bev': bev.detach().cpu(),
#                 'frame_id': zfill6(args.frame_id),
#                 'stage': args.stage,
#                 'checkpoint': os.path.basename(args.checkpoint),
#                 'lidar_override': args.lidar_override}, args.out)
# 
#     print(f"[OK] Saved: {args.out}")
#     print(f"BEV shape: {tuple(bev.shape)}")
# 
# if __name__ == "__main__":
#     main()
# PY
# 
# echo "✅ Teacher BEV..."
# $PY /content/extract_bev_mvxnet.py \
#   --config "$CFG" \
#   --checkpoint "$TEACHER_CKPT" \
#   --kitti_root "$KITTI" \
#   --frame_id "$FRAME_ID" \
#   --stage "$STAGE" \
#   --out "$OUT_DIR/teacher_${FRAME_ID}_${STAGE}.pt"
# 
# echo "✅ Student BEV (Pseudo override)..."
# $PY /content/extract_bev_mvxnet.py \
#   --config "$CFG" \
#   --checkpoint "$STUDENT_CKPT" \
#   --kitti_root "$KITTI" \
#   --frame_id "$FRAME_ID" \
#   --lidar_override "$PSEUDO_DIR/$FRAME_ID.bin" \
#   --stage "$STAGE" \
#   --out "$OUT_DIR/student_${FRAME_ID}_${STAGE}.pt"
# 
# echo "✅ DONE:"
# ls -lah "$OUT_DIR"
#

import os
import torch
import numpy as np
import matplotlib.pyplot as plt

TEACHER_PT = "/content/bev_out/teacher_000000_middle.pt"
STUDENT_PT = "/content/bev_out/student_000000_middle.pt"
OUT_DIR = "/content/bev_vis"
os.makedirs(OUT_DIR, exist_ok=True)

def bev_to_map(bev, mode="mean_abs"):
    # bev: (1,C,H,W) or (C,H,W)
    if bev.ndim == 4:
        bev = bev[0]
    if mode == "mean_abs":
        m = bev.abs().mean(dim=0)
    elif mode == "l2":
        m = torch.sqrt((bev ** 2).sum(dim=0) + 1e-12)
    elif mode == "max_abs":
        m = bev.abs().max(dim=0).values
    else:
        raise ValueError("mode must be one of: mean_abs, l2, max_abs")
    return m

def normalize_01(x):
    x = x.detach().cpu().float()
    x = x - x.min()
    x = x / (x.max() + 1e-12)
    return x

t = torch.load(TEACHER_PT)["bev"].float()
s = torch.load(STUDENT_PT)["bev"].float()

t_map = normalize_01(bev_to_map(t, "mean_abs"))
s_map = normalize_01(bev_to_map(s, "mean_abs"))
d_map = normalize_01((t_map - s_map).abs())

# Teacher
plt.figure()
plt.title("Teacher BEV (mean_abs)")
plt.imshow(t_map.numpy())
plt.axis("off")
plt.savefig(os.path.join(OUT_DIR, "teacher_mean_abs.png"), dpi=200, bbox_inches="tight")
plt.show()

# Student
plt.figure()
plt.title("Student BEV (mean_abs)")
plt.imshow(s_map.numpy())
plt.axis("off")
plt.savefig(os.path.join(OUT_DIR, "student_mean_abs.png"), dpi=200, bbox_inches="tight")
plt.show()

# Diff
plt.figure()
plt.title("Diff |Teacher-Student| (mean_abs)")
plt.imshow(d_map.numpy())
plt.axis("off")
plt.savefig(os.path.join(OUT_DIR, "diff_mean_abs.png"), dpi=200, bbox_inches="tight")
plt.show()

print("Saved to:", OUT_DIR)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile auto_train.py
# import os
# import shutil
# import numpy as np
# import glob
# import sys
# # 경로 문제 방지를 위해 시스템 경로 추가
# sys.path.append('/content/mmdetection3d')
# 
# from mmdet3d.utils import register_all_modules
# from mmengine.config import Config
# from mmengine.runner import Runner
# from tqdm import tqdm
# 
# # =================================================================
# # [설정] ZIP 파일 경로 (여기를 사용자님 경로로!)
# # =================================================================
# ZIP_PATH = '/content/drive/MyDrive/Kitti_3D_Project/glpn_output.zip'
# SOURCE_PATH = '/content/drive/MyDrive/Kitti_3D_Project/glpn_output' # 폴더일 경우 대비
# TEACHER_PATH = '/content/drive/MyDrive/Kitti_3D_Project/checkpoints/mxvnet_best.pth'
# DATA_ROOT = '/content/kitti_pseudo_lidar'
# VELODYNE_DIR = os.path.join(DATA_ROOT, 'training/velodyne_reduced')
# 
# def main():
#     print(f"🚀 [1단계] 데이터 찾기 시작...")
# 
#     # 1. 파일 찾기 (Zip이든 폴더든 싹 다 뒤짐)
#     # 폴더 검색
#     files = glob.glob(os.path.join(SOURCE_PATH, '**', '*.npy'), recursive=True) + \
#             glob.glob(os.path.join(SOURCE_PATH, '**', '*.bin'), recursive=True)
# 
#     # 만약 폴더에 없으면 Zip 해제 시도 (혹시 모르니)
#     if len(files) == 0 and os.path.exists(ZIP_PATH):
#         import zipfile
#         print("   -> 폴더에 파일이 없어 ZIP 해제를 시도합니다.")
#         temp_zip_dir = '/content/temp_zip_extract'
#         with zipfile.ZipFile(ZIP_PATH, 'r') as z:
#             z.extractall(temp_zip_dir)
#         files = glob.glob(os.path.join(temp_zip_dir, '**', '*.npy'), recursive=True) + \
#                 glob.glob(os.path.join(temp_zip_dir, '**', '*.bin'), recursive=True)
# 
#     if len(files) == 0:
#         print("❌ [실패] 데이터를 찾을 수 없습니다. 경로를 확인해주세요.")
#         return
# 
#     print(f"   ✅ 데이터 파일 {len(files)}개 확보! 변환 시작...")
# 
#     # 2. 데이터 변환 (.bin)
#     if os.path.exists(VELODYNE_DIR): shutil.rmtree(VELODYNE_DIR)
#     os.makedirs(VELODYNE_DIR, exist_ok=True)
# 
#     for src in tqdm(files):
#         try:
#             if src.endswith('.npy'):
#                 points = np.load(src)
#             else:
#                 points = np.fromfile(src, dtype=np.float32).reshape(-1, 4)
# 
#             # .bin 저장
#             name = os.path.splitext(os.path.basename(src))[0] + '.bin'
#             dst = os.path.join(VELODYNE_DIR, name)
#             points.astype(np.float32).tofile(dst)
#         except Exception as e:
#             print(f"   ⚠️ 파일 에러 (건너뜀): {src}")
# 
#     # 3. 학습 정보 생성 (create_data.py 호출)
#     print("\n🚀 [2단계] 정보 파일(.pkl) 생성 중...")
#     os.system(f"python /content/mmdetection3d/tools/create_data.py kitti --root-path {DATA_ROOT} --out-dir {DATA_ROOT} --extra-tag kitti")
# 
#     # 4. 학습 시작
#     print("\n🚀 [3단계] 학습 시작 (Config 로드)")
#     register_all_modules(init_default_scope=True)
#     cfg = Config.fromfile('/content/mmdetection3d/configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py')
# 
#     # 경로 강제 연결
#     cfg.data_root = DATA_ROOT
#     cfg.train_dataloader.dataset.data_root = DATA_ROOT
#     cfg.train_dataloader.dataset.data_prefix = dict(pts='training/velodyne_reduced')
#     cfg.train_dataloader.dataset.ann_file = 'kitti_infos_train.pkl'
# 
#     cfg.val_dataloader.dataset.data_root = DATA_ROOT
#     cfg.val_dataloader.dataset.data_prefix = dict(pts='training/velodyne_reduced')
#     cfg.val_dataloader.dataset.ann_file = 'kitti_infos_val.pkl'
# 
#     cfg.test_dataloader.dataset.data_root = DATA_ROOT
#     cfg.test_dataloader.dataset.data_prefix = dict(pts='training/velodyne_reduced')
#     cfg.test_dataloader.dataset.ann_file = 'kitti_infos_val.pkl'
# 
#     # 파라미터
#     cfg.train_dataloader.batch_size = 4
#     cfg.train_cfg.max_epochs = 50
#     cfg.work_dir = '/content/drive/MyDrive/Kitti_3D_Project/work_dirs/final_kd_run'
# 
#     # Teacher 모델 로드
#     if os.path.exists(TEACHER_PATH):
#         print(f"   ✅ Teacher 모델 로드: {TEACHER_PATH}")
#         cfg.load_from = TEACHER_PATH
# 
#     # 실행
#     runner = Runner.from_cfg(cfg)
#     runner.train()
# 
# if __name__ == "__main__":
#     main()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_all_in_one.py
# import os
# import zipfile
# import numpy as np
# import torch
# from mmengine.config import Config
# from mmengine.runner import Runner
# from mmdet3d.utils import register_all_modules
# from tqdm import tqdm
# import shutil
# 
# # =================================================================
# # 1. [여기만 수정] 경로 설정
# # =================================================================
# # (1) GLPN 결과물 (Zip 파일) 경로
# ZIP_PATH = '/content/drive/MyDrive/Colab Notebooks/3d_project/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class-8963258a.pth'
# 
# # (2) Teacher 모델 (MXVNet) 경로
# TEACHER_PATH = '/content/drive/MyDrive/Colab Notebooks/3d_project/pseudo_velodyne.tar.gz'
# 
# # (3) 스케일링 값 (3Dbbox 프로젝트에서 구한 값, 모르면 1.0)
# SCALE_FACTOR = 1.0
# # =================================================================
# 
# # 고정 경로 (수정 불필요)
# DATA_ROOT = '/content/kitti_pseudo_lidar'
# VELODYNE_DIR = os.path.join(DATA_ROOT, 'training/velodyne_reduced')
# WORK_DIR = '/content/drive/MyDrive/Kitti_3D_Project/work_dirs/final_kd_run'
# 
# def step1_prepare_data():
#     print(f"\n🚀 [1단계] 데이터 압축 해제 및 스케일링 시작...")
# 
#     # 초기화
#     if os.path.exists(VELODYNE_DIR): shutil.rmtree(VELODYNE_DIR)
#     os.makedirs(VELODYNE_DIR, exist_ok=True)
# 
#     # 임시 압축 해제
#     temp_dir = '/content/temp_unzip'
#     if os.path.exists(temp_dir): shutil.rmtree(temp_dir)
#     os.makedirs(temp_dir, exist_ok=True)
# 
#     print(f"   - Zip 파일: {ZIP_PATH}")
#     with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
#         zip_ref.extractall(temp_dir)
# 
#     # 파일 변환 (npy/bin -> scaled bin)
#     files = []
#     for r, d, f in os.walk(temp_dir):
#         for file in f:
#             if file.endswith(('.npy', '.bin')):
#                 files.append(os.path.join(r, file))
# 
#     print(f"   - 변환 대상: {len(files)}개 파일 (스케일: x{SCALE_FACTOR})")
# 
#     for src in tqdm(files):
#         # 로드
#         if src.endswith('.npy'):
#             points = np.load(src)
#         else:
#             points = np.fromfile(src, dtype=np.float32).reshape(-1, 4)
# 
#         # 스케일링 (XYZ 좌표 보정)
#         points[:, :3] *= SCALE_FACTOR
# 
#         # 저장 (.bin)
#         name = os.path.splitext(os.path.basename(src))[0] + '.bin'
#         dst = os.path.join(VELODYNE_DIR, name)
#         points.astype(np.float32).tofile(dst)
# 
#     print("   ✅ 데이터 준비 완료!")
# 
# def step2_create_infos():
#     print(f"\n🚀 [2단계] MMDetection3D용 정보 파일(.pkl) 생성")
#     # create_data.py 실행과 동일한 효과
#     # 여기서는 간단하게 cmd 호출
#     cmd = f"python /content/mmdetection3d/tools/create_data.py kitti --root-path {DATA_ROOT} --out-dir {DATA_ROOT} --extra-tag kitti"
#     os.system(cmd)
#     print("   ✅ 정보 생성 완료!")
# 
# def step3_train():
#     print(f"\n🚀 [3단계] KD 학습 시작 (Teacher: MXVNet)")
#     register_all_modules(init_default_scope=True)
# 
#     # Config 로드
#     cfg = Config.fromfile('/content/mmdetection3d/configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-3class.py')
# 
#     # 경로 강제 연결
#     cfg.data_root = DATA_ROOT
#     cfg.train_dataloader.dataset.data_root = DATA_ROOT
#     cfg.train_dataloader.dataset.data_prefix = dict(pts='training/velodyne_reduced')
#     cfg.train_dataloader.dataset.ann_file = 'kitti_infos_train.pkl'
# 
#     cfg.val_dataloader.dataset.data_root = DATA_ROOT
#     cfg.val_dataloader.dataset.data_prefix = dict(pts='training/velodyne_reduced')
#     cfg.val_dataloader.dataset.ann_file = 'kitti_infos_val.pkl'
# 
#     # 학습 설정
#     cfg.train_dataloader.batch_size = 4
#     cfg.train_cfg.max_epochs = 50
#     cfg.work_dir = WORK_DIR
# 
#     # Teacher 로드
#     if os.path.exists(TEACHER_PATH):
#         print(f"   ✅ Teacher 모델 로드됨: {TEACHER_PATH}")
#         cfg.load_from = TEACHER_PATH
#     else:
#         print(f"   ⚠️ Teacher 모델 없음 ({TEACHER_PATH}). 단독 학습 진행.")
# 
#     # 실행
#     runner = Runner.from_cfg(cfg)
#     runner.train()
# 
# if __name__ == "__main__":
#     step1_prepare_data()
#     step2_create_infos()
#     step3_train()

# 환경 변수 설정 후 우리가 만든 통합 스크립트 실행
!export NUMBA_DISABLE_CUDA=1 && \
 conda run -n openmmlab python -u run_all_in_one.py



"""# 21. 다중 샘플 비교"""

# Commented out IPython magic to ensure Python compatibility.
# # 다중 샘플 비교 시각화
# %%bash
# PY=/content/conda/envs/openmmlab/bin/python
# 
# $PY << 'EOF'
# import matplotlib
# matplotlib.use('Agg')
# 
# import numpy as np
# import matplotlib.pyplot as plt
# import pickle
# import os
# 
# print("=" * 70)
# print("📊 다중 샘플 Detection 비교")
# print("=" * 70)
# 
# LOCAL_KITTI = '/content/data/kitti'
# 
# with open(f'{LOCAL_KITTI}/kitti_infos_train.pkl', 'rb') as f:
#     data = pickle.load(f)
# infos = data['data_list']
# 
# pred_results = {}
# if os.path.exists('/content/inference_results.pkl'):
#     with open('/content/inference_results.pkl', 'rb') as f:
#         pred_results = pickle.load(f)
# 
# SAMPLES = [infos[i] for i in range(min(3, len(infos)))]
# 
# def draw_box_bev(ax, bbox, color, linestyle='-'):
#     x, y, z, dx, dy, dz, yaw = bbox[:7]
#     corners = np.array([[-dx/2, -dy/2], [dx/2, -dy/2],
#                        [dx/2, dy/2], [-dx/2, dy/2], [-dx/2, -dy/2]])
#     cos_y, sin_y = np.cos(yaw), np.sin(yaw)
#     rot = np.array([[cos_y, -sin_y], [sin_y, cos_y]])
#     corners = corners @ rot.T + np.array([x, y])
#     ax.plot(corners[:, 0], corners[:, 1], color=color, linewidth=2, linestyle=linestyle)
# 
# fig, axes = plt.subplots(2, 3, figsize=(18, 10))
# colors = {0: 'blue', 1: 'green', 2: 'red'}
# 
# for idx, sample_info in enumerate(SAMPLES):
#     sample_idx = sample_info['sample_idx']
#     sample_idx_str = f'{sample_idx:06d}'
# 
#     velodyne_file = f'{LOCAL_KITTI}/training/velodyne/{sample_idx_str}.bin'
#     points = np.fromfile(velodyne_file, dtype=np.float32).reshape(-1, 4)
# 
#     mask = (points[:, 0] > 0) & (points[:, 0] < 70) & (np.abs(points[:, 1]) < 40)
#     pts = points[mask]
# 
#     ax_gt = axes[0, idx]
#     ax_gt.scatter(pts[::3, 0], pts[::3, 1], s=0.1, c='gray', alpha=0.3)
#     gt_count = 0
#     if 'instances' in sample_info:
#         for inst in sample_info['instances']:
#             draw_box_bev(ax_gt, inst['bbox_3d'], colors.get(inst['bbox_label_3d'], 'yellow'))
#             gt_count += 1
#     ax_gt.set_title(f"GT - {sample_idx} ({gt_count} obj)", fontweight='bold')
#     ax_gt.set_xlim([0, 70])
#     ax_gt.set_ylim([-40, 40])
#     ax_gt.set_aspect('equal')
#     ax_gt.grid(True, alpha=0.3)
# 
#     ax_pred = axes[1, idx]
#     ax_pred.scatter(pts[::3, 0], pts[::3, 1], s=0.1, c='gray', alpha=0.3)
#     pred_count = 0
#     if sample_idx_str in pred_results:
#         pred_data = pred_results[sample_idx_str]
#         for i in range(len(pred_data['bboxes_3d'])):
#             if pred_data['scores_3d'][i] > 0.3:
#                 draw_box_bev(ax_pred, pred_data['bboxes_3d'][i],
#                             colors.get(pred_data['labels_3d'][i], 'yellow'))
#                 pred_count += 1
#     ax_pred.set_title(f"Pred - {sample_idx} ({pred_count} obj)", fontweight='bold')
#     ax_pred.set_xlim([0, 70])
#     ax_pred.set_ylim([-40, 40])
#     ax_pred.set_aspect('equal')
#     ax_pred.grid(True, alpha=0.3)
# 
#     print(f"   {sample_idx}: GT={gt_count}, Pred={pred_count}")
# 
# from matplotlib.lines import Line2D
# legend_elements = [
#     Line2D([0], [0], color='blue', linewidth=2, label='Pedestrian'),
#     Line2D([0], [0], color='green', linewidth=2, label='Cyclist'),
#     Line2D([0], [0], color='red', linewidth=2, label='Car'),
# ]
# fig.legend(handles=legend_elements, loc='lower center', ncol=3, fontsize=10)
# 
# plt.suptitle("KITTI Multi-Sample Comparison\n(Top: Ground Truth, Bottom: Prediction)",
#              fontsize=14, fontweight='bold')
# plt.tight_layout()
# plt.savefig('/content/multi_sample_comparison.png', dpi=150, bbox_inches='tight')
# plt.close()
# 
# print(f"\n💾 저장됨: /content/multi_sample_comparison.png")
# print("=" * 70)
# EOF

# 다중 샘플 시각화 이미지 표시
from IPython.display import Image, display
display(Image('/content/multi_sample_comparison.png'))